---
-
  hosts: all_ubuntu
  become: yes
  tasks:
    - name: locale-gen en_US.UTF-8
      command: locale-gen "en_US.UTF-8"
    - name: locale-gen ru_RU.UTF-8
      command: locale-gen "ru_RU.UTF-8"
    - name: Remove configuration locales
      file: path=/etc/default/locale state=absent
    - name: Configure locales
      blockinfile:
        dest: /etc/default/locale
        create: yes
        block: |
          LANG="en_US.UTF-8"
          LANGUAGE="en_US:en"
          LC_CTYPE="en_US.UTF-8"
          LC_NUMERIC=ru_RU.UTF-8
          LC_TIME=ru_RU.UTF-8
          LC_COLLATE="en_US.UTF-8"
          LC_MONETARY=ru_RU.UTF-8
          LC_MESSAGES="en_US.UTF-8"
          LC_PAPER=ru_RU.UTF-8
          LC_NAME=ru_RU.UTF-8
          LC_ADDRESS=ru_RU.UTF-8
          LC_TELEPHONE=ru_RU.UTF-8
          LC_MEASUREMENT=ru_RU.UTF-8
          LC_IDENTIFICATION=ru_RU.UTF-8
          LC_ALL=
    - name: Update locales
      command: dpkg-reconfigure locales

