---
- name: "create gitea cont"
  hosts: lxd
  become: yes
  connection: local
  vars:
    profile_name: git
    lxc_ip: 10.9.9.3
    lxc_name: git
  roles:
    - lxd

- name: "bootstrap"
  become: yes
  hosts: gitea
  roles:
    - bootstrap

- name: "install gitea"
  hosts: gitea
  become: yes
  #connection: local
  vars:
    gitea_http_domain: dev.deephost.net
    gitea_root_url: https://dev.deephost.net
    gitea_ssh_domaain: dev.deephost.net
    gitea_db_password: "XXXXXXXXXXXX"
    gitea_mailer_host: m.sdf.li:587
    gitea_mailer_from: git@deephost.net
    gitea_noreplay_address: "deephost.net"
    gitea_mailer_user: "dev@deephost.net"
    gitea_mailer_password: "XXXXX"
  roles:
    - gitea