- name: chocolatey with ansible
  hosts: test_windows
  tasks:
    - name: Disable Domain firewall
      win_firewall:
        state: disabled
        profiles:
        - Domain
      tags: disable_firewall