##### Create lxd container #####
---
- name: "Create lxd container"
  hosts: lxd
  become: yes
  connection: local
  roles:
    - lxd
  vars:
    profile_name: default
    lxc_name: u18-redmine
    limits_cpu: 2
    limits_memory: 4048MB
    security_privileged: "false"
    boot_autostart: "true"
    boot_autostart_delay: "10"

##### Container netplan setup #####
- name: "Container netplan setup"
  become: yes
  hosts: u18-redmine
  roles:
    - netplan
  vars:
    netplan_config_file: /etc/netplan/config.yaml
    netplan_enabled: true
    netplan_apply: true
    netplan_renderer: networkd
    netplan_pri_domain: local
    netplan_configuration:
      network:
        version: 2
        renderer: networkd
        ethernets:
          eth0:
            dhcp4: false
            dhcp6: false
            optional: true
            addresses:
              [192.168.2.35/24]
            gateway4: 192.168.2.3
            nameservers:
              addresses: [192.168.0.6, 192.168.0.24]



##### Container resolvconf setup #####
- name: "Container resolvconf setup"
  become: yes
  hosts: u18-redmine
  roles:
    - resolvconf
  vars:
    resolvconf_enabled: true
    resolvconf_apply: true

##### Container hosts setup #####
- name: "Container hosts setup"
  become: yes
  hosts: u18-redmine
  roles:
    - hosts
  vars:
    hosts_backup: false
    hosts_group: root
    hosts_owner: root
    hosts_mode: 0644
    hosts_hostname_loopback: true
    hosts_inventory_to_hosts: false
    hosts_ipv6: false

##### Container systemd-resolved setup #####
- name: "Container systemd-resolved setup"
  become: yes
  hosts: u18-redmine
  roles:
    - resolved
  vars:
    resolved_enabled: true
    resolved_apply: true
    resolved_config_file: /etc/systemd/resolved.conf
    resolved_configuration:
    dnsstub: no

##### Container locale and timezone setup #####
- name: "Container locale setup"
  become: yes
  hosts: u18-redmine
  roles:
    - locale
  vars:
    locale_enabled: true
    locale_apply: true
    locale: 'en_US.UTF-8'
    language: 'en_US:en'
    timezone: 'Europe/Moscow'

##### Container chrony setup #####
- name: "Container chrony setup"
  become: yes
  hosts: u18-redmine
  roles:
    - chrony
  vars:
    chrony_enabled: true
    chrony_apply: true
    chrony_pkg_state: present
    chrony_service_state: started
    chrony_service_enabled: yes
    chrony_config_server: [192.168.0.3, pool.ntp.org]
    chrony_config_logdir: /var/log/chrony
    chrony_config_extra_options: {}
    chrony_service_name: chrony
    chrony_config_location: /etc/chrony/chrony.conf
    chrony_config_driftfile: /var/lib/chrony/chrony.drift
    chrony_config_keyfile: /etc/chrony/chrony.keys


##### Container sshd setup #####
- name: "Container sshd setup"
  become: yes
  hosts: u18-redmine
  roles:
    - openssh-server
  vars:
    sshd_enabled: true
    sshd_apply: true
    sshd_pkg_state: present
    sshd_service_state: started
    sshd_service_enabled: yes
    sshd_service_name: sshd
    sshd_config_location: /etc/ssh/sshd_config

##### Container users setup #####
- name: "Container users setup"
  become: yes
  hosts: u18-redmine
  roles:
    - adduser
  vars:
    adduser_user_name: demonium
    adduser_user_home: '/home/demonium'
    adduser_user_home_perms: '0700'
    adduser_user_comments: "Valentin Efimov"
    adduser_sudoroot: true
    adduser_sudoroot_nopasswd: true
    adduser_sudoroot_nopasswd_cmd: 'ALL'
    adduser_password: '$6$.AsX.MGDf1ijU$oHxGnGikaGj8E.v9z2TXpTRP2Nq0KxPnEXgkj0Yl8DqwMmyMdPPUp8YHNlKT6OGAbf6QNPnnjmSTPXFLH9w.D.'
    adduser_password_update: on_create
    adduser_shell: '/bin/bash'
    adduser_groups:
    - sudo
    adduser_public_keys:
    - demonium.pub

##### Container apt setup #####
- name: "Container apt setup"
  become: yes
  hosts: u18-redmine
  roles:
    - apt
  vars:
    apt_enabled: true
    apt_proxy_enabled: false
    apt_packages: [mc, htop, lsof, python-psycopg2, ruby, ruby-dev, libwbxml2-dev, libxslt1-dev, libiconv-hook-dev, build-essential, zlib1g-dev, libssl-dev, libreadline-dev, libyaml-dev, libcurl4-openssl-dev, libffi-dev, imagemagick, libmagick++-dev, fonts-takao-pgothic, libapr1-dev, libaprutil1-dev, subversion, git]
    apt_remove_packages: [snapd]
    apt_url_keys: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    apt_repos: deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main

##### Container apache2 setup #####
- name: "Container apache2 setup"
  become: yes
  hosts: u18-redmine
  roles:
    - apache
  vars:
    apache_listen_ip: "*"
    apache_listen_port: 80
    apache_create_vhosts: true
    apache_vhosts_filename: "vhosts.conf"
    apache_vhosts_template: "vhosts.conf.j2"
    apache_remove_default_vhost: true
    apache_global_vhost_settings: |
      DirectoryIndex index.html
    apache_vhosts:
      - servername: "redmine.local"
        documentroot: "/var/www/html"
    apache_mods_enabled:
      - rewrite.load
    apache_state: started
    apache_restart_state: restarted
    apache_packages_state: latest

##### Container postgresql setup #####
- name: "Container postgresql setup"
  become: yes
  hosts: u18-redmine
  roles:
    - postgresql
  vars:
     postgres_users_no_log: false






