---

- name: "Create Gitea user"
  user:
    name: "git"
    home: "/home/git"
    shell: "/bin/bash"
    system: yes

- name: "Install git and ssh"
  apt:
    pkg:
      - git
      - openssh-server
    state: present

- name: "Check gitea version"
  shell: "set -eo pipefail; /usr/local/bin/gitea -v | cut -d' ' -f 3"
  register: gitea_active_version
  changed_when: false
  failed_when: false
  when: gitea_version_check|bool

- name: "Download the binary"
  get_url:
    url: "{{ gitea_dl_url }}/v{{ gitea_version }}/gitea-{{ gitea_version }}-linux-{{ gitea_arch }}"
    dest: /usr/local/bin/gitea
    owner: root
    group: root
    mode: 0755
    force: true
  notify: "Restart gitea"
  when: (not gitea_version_check|bool) or (gitea_active_version.stdout != gitea_version)


- name: "Create config and data directory"
  file:
    path: "{{ item }}"
    state: directory
    owner: "git"
  with_items:
    - "/etc/gitea"
    - "/var/lib/gitea/"
    - "/var/lib/gitea/data"
    - "/var/lib/gitea/custom"
    - "/var/lib/gitea/custom/https"
    - "/var/lib/gitea/custom/mailer"

- name: "Configure gitea"
  template:
    src: app.ini.j2
    dest: /etc/gitea/app.ini
    owner: "git"
    mode: 0600
  notify: "Restart gitea"

- name: "Service gitea"
  service:
    name: gitea
    state: started
    enabled: true
  when: ansible_service_mgr == "systemd"

