network:
  version: 2
  renderer: networkd

  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
      addresses:
          [192.168.2.25/24]
      gateway4: 192.168.2.3
      nameservers:
          addresses: [192.168.0.6, 192.168.0.24]

